import {
  GraduationCap,
  Percent,
  BookOpen,
  FileText,
  Layers,
  Scale,
  Clock,
  CalendarCheck,
  Trophy,
  ListOrdered,
  GitCompare,
  ListTree,
  Briefcase,
  HelpCircle,
  CalendarRange,
  Calculator,
  Atom,
  Target,
  ClipboardList,
  FlaskConical,
  Sigma,
  Lightbulb,
  Package,
  Library,
  type LucideIcon,
} from 'lucide-react'

/** Single source of truth for tool.icon string → Lucide component */
export const TOOL_ICON_MAP: Record<string, LucideIcon> = {
  GraduationCap,
  Percent,
  BookOpen,
  FileText,
  Layers,
  Scale,
  Clock,
  CalendarCheck,
  Trophy,
  ListOrdered,
  GitCompare,
  ListTree,
  Briefcase,
  HelpCircle,
  CalendarRange,
  Calculator,
  Atom,
  Target,
  ClipboardList,
  FlaskConical,
  Sigma,
  Lightbulb,
  Package,
  Library,
}

export function getToolIcon(name: string): LucideIcon {
  return TOOL_ICON_MAP[name] || GraduationCap
}
